### ISSUE TITLE
Add arguments to avoid hard-coding of protobuf_path and data_root_path

### ISSUE THREAD

**Issue by francescomilano172** [ethz-asl/scenenet_ros_tools#7]
Would it be possible to add two arguments to avoid hard-coding the path to the protobuf file and the type of dataset ('train' or 'val')? Something like https://github.com/francescomilano172/scenenet_ros_tools/commit/0a18291193b00ea0f6eb28cde24b4e9c3f02d39d (forked repo)? I find this handy when generating data automatically from a script.

**Comment by francescomilano172** [comment]
Ok done, I wasn't sure if I could do it

**Comment by margaritaG** [comment]
Fixed in #8.
